name = "mintcom"
compatibility_date = "2024-09-23"
main = "src/worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
API_TARGET = "https://grateful-liberation-production-d036.up.railway.app"
VITE_GA_MEASUREMENT_ID = "G-QHV2SVCG99"
VITE_QA_ACCESS_KEY = "fDJg_HNS87_R5QNjWWt-cxJXf557sMBI"
